# This file was generated by GoReleaser. DO NOT EDIT.
class Kagome < Formula
  desc "Self-contained Japanese Morphological Analyzer written in pure Go."
  homepage "https://github.com/ikawaha/kagome"
  version "2.4.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ikawaha/kagome/releases/download/v2.4.3/kagome_2.4.3_darwin_amd64.tar.gz"
    sha256 "1342fdbe5059b130e596411b1ca3cdf4b245dd45b94de0d71d7cc87189826ad3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ikawaha/kagome/releases/download/v2.4.3/kagome_2.4.3_linux_amd64.tar.gz"
    sha256 "ca04466ca308f55f486c3ddc11a580d9b3c75baf0e2cce7b3e8bce04cfb98d2a"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/ikawaha/kagome/releases/download/v2.4.3/kagome_2.4.3_linux_armv6.tar.gz"
    sha256 "85264db413c1e9e78cc3523252853b4f3b3421f16a8dc4489e2019fb89aa270c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ikawaha/kagome/releases/download/v2.4.3/kagome_2.4.3_linux_arm64.tar.gz"
    sha256 "8e2d353740474e450441930baa990448720863fe365650411441bb977012d8ae"
  end

  def install
    bin.install "kagome"
  end

  test do
    system "#{bin}/kagome version"
  end
end
