# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kagome < Formula
  desc "Self-contained Japanese Morphological Analyzer written in pure Go."
  homepage "https://github.com/ikawaha/kagome"
  version "2.6.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ikawaha/kagome/releases/download/v2.6.2/kagome_2.6.2_darwin_amd64.tar.gz"
      sha256 "0a3f22fdadf7d0cdd40d7276612c2349934df1c45a1b298ac61226824bea0972"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ikawaha/kagome/releases/download/v2.6.2/kagome_2.6.2_darwin_arm64.tar.gz"
      sha256 "529ae92756051578b18286e987359c07e176f186c456ec0543557caa22131ff7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ikawaha/kagome/releases/download/v2.6.2/kagome_2.6.2_linux_amd64.tar.gz"
      sha256 "49c660a1010ce0c1210022f134da6a5546e5e76e19987019c779a3c8b26cc502"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ikawaha/kagome/releases/download/v2.6.2/kagome_2.6.2_linux_armv6.tar.gz"
      sha256 "cc0247998b73b481b94f72456b30544cdc00e065c5c28c2840f9dcd718dd2576"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ikawaha/kagome/releases/download/v2.6.2/kagome_2.6.2_linux_arm64.tar.gz"
      sha256 "ce3ceeb7735725b8cddd9fc2a03b91bd72d777a391a927b6af0610fc1d070913"
    end
  end

  def install
    bin.install "kagome"
  end

  test do
    system "#{bin}/kagome version"
  end
end
