# This file was generated by GoReleaser. DO NOT EDIT.
class Kagome < Formula
  desc "Self-contained Japanese Morphological Analyzer written in pure Go."
  homepage "https://github.com/ikawaha/kagome"
  version "2.4.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ikawaha/kagome/releases/download/v2.4.1/kagome_2.4.1_darwin_amd64.tar.gz"
    sha256 "b2a35773e0b178e85c53de4a59ce5d03ec37af62252be470da9bc0523793251c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ikawaha/kagome/releases/download/v2.4.1/kagome_2.4.1_linux_amd64.tar.gz"
    sha256 "f727a7854570f47c6ec723ae3da2d09979ae859c2b138ca2f471fdf1b08e5a55"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/ikawaha/kagome/releases/download/v2.4.1/kagome_2.4.1_linux_armv6.tar.gz"
    sha256 "27c215ecc6c79cd4e40b3870a4f2a0ca2639985de4f9d2b877b782eb2ea99a20"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ikawaha/kagome/releases/download/v2.4.1/kagome_2.4.1_linux_arm64.tar.gz"
    sha256 "ed674c5f2263be47a371c26b5bba4bca304fd2cc093aaf182e3e3d6fd3a2d7f4"
  end

  def install
    bin.install "kagome"
  end

  test do
    system "#{bin}/kagome version"
  end
end
